<?php
/**
 * InlineResponse20030Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PAYCOMET REST API
 *
 * PAYCOMET API REST for customers.
 *
 * OpenAPI spec version: 2.21.0
 * Contact: tecnico@paycomet.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InlineResponse20030Test Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse20030
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse20030Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse20030"
     */
    public function testInlineResponse20030()
    {
    }

    /**
     * Test attribute "error_code"
     */
    public function testPropertyErrorCode()
    {
    }

    /**
     * Test attribute "ivr_response"
     */
    public function testPropertyIvrResponse()
    {
    }

    /**
     * Test attribute "ivr_session_state"
     */
    public function testPropertyIvrSessionState()
    {
    }

    /**
     * Test attribute "ivr_session_result"
     */
    public function testPropertyIvrSessionResult()
    {
    }

    /**
     * Test attribute "ivr_time_left"
     */
    public function testPropertyIvrTimeLeft()
    {
    }

    /**
     * Test attribute "ivr_digit_pan"
     */
    public function testPropertyIvrDigitPan()
    {
    }

    /**
     * Test attribute "ivr_digit_exp"
     */
    public function testPropertyIvrDigitExp()
    {
    }

    /**
     * Test attribute "ivr_digit_cvc"
     */
    public function testPropertyIvrDigitCvc()
    {
    }
}
