<?php
/**
 * InlineResponse20014PaymentHistoryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PAYCOMET REST API
 *
 * PAYCOMET API REST for customers.
 *
 * OpenAPI spec version: 2.21.0
 * Contact: tecnico@paycomet.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InlineResponse20014PaymentHistoryTest Class Doc Comment
 *
 * @category    Class
 * @description Log of operations
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse20014PaymentHistoryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse20014PaymentHistory"
     */
    public function testInlineResponse20014PaymentHistory()
    {
    }

    /**
     * Test attribute "operation_id"
     */
    public function testPropertyOperationId()
    {
    }

    /**
     * Test attribute "method_id"
     */
    public function testPropertyMethodId()
    {
    }

    /**
     * Test attribute "timestamp"
     */
    public function testPropertyTimestamp()
    {
    }

    /**
     * Test attribute "order"
     */
    public function testPropertyOrder()
    {
    }

    /**
     * Test attribute "operation_type"
     */
    public function testPropertyOperationType()
    {
    }

    /**
     * Test attribute "operation_name"
     */
    public function testPropertyOperationName()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "state_name"
     */
    public function testPropertyStateName()
    {
    }

    /**
     * Test attribute "response"
     */
    public function testPropertyResponse()
    {
    }

    /**
     * Test attribute "terminal"
     */
    public function testPropertyTerminal()
    {
    }

    /**
     * Test attribute "terminal_name"
     */
    public function testPropertyTerminalName()
    {
    }

    /**
     * Test attribute "user"
     */
    public function testPropertyUser()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "amount_display"
     */
    public function testPropertyAmountDisplay()
    {
    }

    /**
     * Test attribute "error_code"
     */
    public function testPropertyErrorCode()
    {
    }

    /**
     * Test attribute "error_description"
     */
    public function testPropertyErrorDescription()
    {
    }

    /**
     * Test attribute "fee_euro"
     */
    public function testPropertyFeeEuro()
    {
    }

    /**
     * Test attribute "fee_percent"
     */
    public function testPropertyFeePercent()
    {
    }

    /**
     * Test attribute "original_ip"
     */
    public function testPropertyOriginalIp()
    {
    }

    /**
     * Test attribute "pan"
     */
    public function testPropertyPan()
    {
    }

    /**
     * Test attribute "scoring"
     */
    public function testPropertyScoring()
    {
    }

    /**
     * Test attribute "merchant_bank"
     */
    public function testPropertyMerchantBank()
    {
    }

    /**
     * Test attribute "bic_code"
     */
    public function testPropertyBicCode()
    {
    }

    /**
     * Test attribute "product_description"
     */
    public function testPropertyProductDescription()
    {
    }

    /**
     * Test attribute "card_type"
     */
    public function testPropertyCardType()
    {
    }

    /**
     * Test attribute "card_category"
     */
    public function testPropertyCardCategory()
    {
    }

    /**
     * Test attribute "card_brand"
     */
    public function testPropertyCardBrand()
    {
    }

    /**
     * Test attribute "card_country"
     */
    public function testPropertyCardCountry()
    {
    }

    /**
     * Test attribute "secure"
     */
    public function testPropertySecure()
    {
    }

    /**
     * Test attribute "split_id"
     */
    public function testPropertySplitId()
    {
    }

    /**
     * Test attribute "issuer_bank"
     */
    public function testPropertyIssuerBank()
    {
    }

    /**
     * Test attribute "auth_code"
     */
    public function testPropertyAuthCode()
    {
    }
}
