<?php
/**
 * V1formPaymentMerchantDataThreeDSRequestorAuthenticationInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PAYCOMET REST API
 *
 * PAYCOMET API REST for customers.
 *
 * OpenAPI spec version: 2.21.0
 * Contact: tecnico@paycomet.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * V1formPaymentMerchantDataThreeDSRequestorAuthenticationInfoTest Class Doc Comment
 *
 * @category    Class
 * @description Node with additional information on how the client was authenticated at the start of the session in the business account
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class V1formPaymentMerchantDataThreeDSRequestorAuthenticationInfoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "V1formPaymentMerchantDataThreeDSRequestorAuthenticationInfo"
     */
    public function testV1formPaymentMerchantDataThreeDSRequestorAuthenticationInfo()
    {
    }

    /**
     * Test attribute "three_ds_req_auth_data"
     */
    public function testPropertyThreeDsReqAuthData()
    {
    }

    /**
     * Test attribute "three_ds_req_auth_method"
     */
    public function testPropertyThreeDsReqAuthMethod()
    {
    }

    /**
     * Test attribute "three_ds_req_auth_timestamp"
     */
    public function testPropertyThreeDsReqAuthTimestamp()
    {
    }
}
