<?php
/**
 * V1launchpadsubscriptionMerchantDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PAYCOMET REST API
 *
 * PAYCOMET API REST for customers.
 *
 * OpenAPI spec version: 2.21.0
 * Contact: tecnico@paycomet.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * V1launchpadsubscriptionMerchantDataTest Class Doc Comment
 *
 * @category    Class
 * @description Client authentication information. The more information is provided in this field, the more likely the authorisation of the operation will be without requiring additional authentication. For this reason, it is recommended to send as much information as possible.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class V1launchpadsubscriptionMerchantDataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "V1launchpadsubscriptionMerchantData"
     */
    public function testV1launchpadsubscriptionMerchantData()
    {
    }

    /**
     * Test attribute "customer"
     */
    public function testPropertyCustomer()
    {
    }

    /**
     * Test attribute "shipping"
     */
    public function testPropertyShipping()
    {
    }

    /**
     * Test attribute "billing"
     */
    public function testPropertyBilling()
    {
    }

    /**
     * Test attribute "acct_id"
     */
    public function testPropertyAcctId()
    {
    }

    /**
     * Test attribute "acct_info"
     */
    public function testPropertyAcctInfo()
    {
    }

    /**
     * Test attribute "merchant_risk_indicator"
     */
    public function testPropertyMerchantRiskIndicator()
    {
    }

    /**
     * Test attribute "three_ds_requestor_authentication_info"
     */
    public function testPropertyThreeDsRequestorAuthenticationInfo()
    {
    }

    /**
     * Test attribute "shopping_cart"
     */
    public function testPropertyShoppingCart()
    {
    }

    /**
     * Test attribute "addr_match"
     */
    public function testPropertyAddrMatch()
    {
    }

    /**
     * Test attribute "purchase_instal_data"
     */
    public function testPropertyPurchaseInstalData()
    {
    }

    /**
     * Test attribute "recurring_expiry"
     */
    public function testPropertyRecurringExpiry()
    {
    }

    /**
     * Test attribute "recurring_frequency"
     */
    public function testPropertyRecurringFrequency()
    {
    }
}
