<?php
/**
 * V1subscriptionPaymentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PAYCOMET REST API
 *
 * PAYCOMET API REST for customers.
 *
 * OpenAPI spec version: 2.21.0
 * Contact: tecnico@paycomet.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * V1subscriptionPaymentTest Class Doc Comment
 *
 * @category    Class
 * @description V1subscriptionPayment
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class V1subscriptionPaymentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "V1subscriptionPayment"
     */
    public function testV1subscriptionPayment()
    {
    }

    /**
     * Test attribute "terminal"
     */
    public function testPropertyTerminal()
    {
    }

    /**
     * Test attribute "method_id"
     */
    public function testPropertyMethodId()
    {
    }

    /**
     * Test attribute "order"
     */
    public function testPropertyOrder()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "original_ip"
     */
    public function testPropertyOriginalIp()
    {
    }

    /**
     * Test attribute "id_user"
     */
    public function testPropertyIdUser()
    {
    }

    /**
     * Test attribute "token_user"
     */
    public function testPropertyTokenUser()
    {
    }

    /**
     * Test attribute "secure"
     */
    public function testPropertySecure()
    {
    }

    /**
     * Test attribute "scoring"
     */
    public function testPropertyScoring()
    {
    }

    /**
     * Test attribute "product_description"
     */
    public function testPropertyProductDescription()
    {
    }

    /**
     * Test attribute "merchant_descriptor"
     */
    public function testPropertyMerchantDescriptor()
    {
    }

    /**
     * Test attribute "user_interaction"
     */
    public function testPropertyUserInteraction()
    {
    }

    /**
     * Test attribute "escrow_targets"
     */
    public function testPropertyEscrowTargets()
    {
    }

    /**
     * Test attribute "trx_type"
     */
    public function testPropertyTrxType()
    {
    }

    /**
     * Test attribute "sca_exception"
     */
    public function testPropertyScaException()
    {
    }

    /**
     * Test attribute "url_ok"
     */
    public function testPropertyUrlOk()
    {
    }

    /**
     * Test attribute "url_ko"
     */
    public function testPropertyUrlKo()
    {
    }

    /**
     * Test attribute "notify_direct_payment"
     */
    public function testPropertyNotifyDirectPayment()
    {
    }

    /**
     * Test attribute "merchant_data"
     */
    public function testPropertyMerchantData()
    {
    }
}
